### PR TITLE
scoreboard tests

### PR DESCRIPTION
**Pull request by kashyapgajera**
codeclimate changes

reviewed changes

### CODE REVIEW

**Comment by prasadtalasila** [comment]
Please check the travis build log starting on [line-481](https://travis-ci.org/prasadtalasila/JavaAutolab/builds/220520949#L481). Tests 3-7 of scoreboard.bats are failing.

**Comment by kashyapgajera** [comment]
It is not failing. It tries to make an ssh connection (i don't get these
messages in local testing) and gives the output.
All the tests are passing, I can see an ok in all the tests.

**Comment by kashyapgajera** [comment]
Also the build fails if any of the tests are failing which is not the case
here.

**Comment by prasadtalasila** [comment]
Correction. The tests aren't failing. See the log below.

```
=========scoreboard tests=========
1..8
ok 1 empty scoreboard of a fresh lab
ok 2 empty scoreboard of an inactive lab
The authenticity of host 'localhost (127.0.0.1)' can't be established.
ECDSA key fingerprint is 9f:4a:e2:fa:a7:58:55:df:3a:56:6b:49:5e:02:f3:fd.
Are you sure you want to continue connecting (yes/no)? ok 3 scoreboard after one evaluation
...
ok 8 scoreboards two concurrent, inactive labs
```
The BATS success message is printed after certificate warning. You can either redirect stderror to /dev/null or utilize the stackoverflow answer indicated before to get clean output.

**Comment by prasadtalasila** [comment]
@kashyapgajera please fix the certificate issues and codeclimate issues. Rebase to a single commit and open a fresh pull request.

**Pull request closed without merging**
